enum currType { //what the pico needs to do
    //^ Linetrack
    TCS_LINETRACK = -1,
    EMPTY_LINETRACK = 0,
    LEFT_GREEN = 1,
    RIGHT_GREEN = 2,
    DOUBLE_GREEN = 3,
    RED = 4,
    BEFORE_BLUE_TURN = 7,
    BLUE = 8,
    LINEGAP = 12,
    BLUE_PICKUP = 26,
    BEFORE_OBSTACLE_REVERSE = 30,
    BEFORE_OBSTACLE_TURN = 31,
    OBSTACLE = 32,
    //^ Evac stuff
    // CHECK_FOR_EVAC = 49,
    EVAC_INIT = 50,
    EVAC_PICKUP = 51,
    WALLTRACK = 60, //^ basically no ball walltrack
    WALLTRACK_OOR = 61,
    WALLTRACK_HITWALL = 62,
    WALLTRACK_WALLGAP = 63,
    BALLTRACK = 65,
    CENTERING_FOR_DEPOSIT = 70,
    HEAD_TO_DEPOSIT = 71,
    DEPOSIT = 80,
    POST_DEPOSIT = 81,
    REVERSE_FROM_ALIVE = 74,
    REVERSE_FROM_DEAD = 75,
    AFTER_DEAD = 89,
    EXIT_EVAC = 90,
    EXIT_EVAC_TURN = 91,
    EVAC_FRONT_LEFT_SEE_OUT = 93,
    //^ Forced stuff
    STOP = 100,
    MOVE_DIST = 101,
    TURN_ANGLE = 102,
    TURN_TIME = 103,
    //^ POST SHIT
    POST_DOUBLE_GREEN = 200,
    AFTER_BLUE_INIT = 23,
    AFTER_BLUE_REVERSE = 24,
    AFTER_BLUE_TURN = 25,
    AFTER_OBSTACLE_TURN = 33,
};